services:
  kafka-1:
    image: apache/kafka:3.7.0
    hostname: kafka-1
    container_name: kafka-1
    ports:
      - "9092:9092"
    volumes:
      - ./kafka-1/data:/kafka/data
      - ./kafka-1/kraft.properties:/kafka/config/kraft.properties
      - ./entrypoint.sh:/kafka/entrypoint.sh
    environment:
#      KAFKA_NODE_ID: 1
#      KAFKA_PROCESS_ROLES: broker,controller
#      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
#      KAFKA_LISTENERS: PLAINTEXT://kafka-1:29092,CONTROLLER://kafka-1:9093,PLAINTEXT_HOST://0.0.0.0:9092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:29092,PLAINTEXT_HOST://localhost:9092
#      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_LOG_DIRS: /kafka/data
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
#    command: [ "sh", "-c", "/opt/kafka/bin/kafka-server-start.sh /kafka/config/kraft.properties" ]
    command: [ "sh", "-c", "/kafka/entrypoint.sh" ]
    networks:
      - kafka-net
  kafka-2:
    image: apache/kafka:3.7.0
    hostname: kafka-2
    container_name: kafka-2
    ports:
      - "9094:9094"
    volumes:
      - ./kafka-2/data:/kafka/data
      - ./kafka-2/kraft.properties:/kafka/config/kraft.properties
      - ./entrypoint.sh:/kafka/entrypoint.sh
    environment:
#      KAFKA_NODE_ID: 2
#      KAFKA_PROCESS_ROLES: broker,controller
#      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
#      KAFKA_LISTENERS: PLAINTEXT://kafka-2:29092,CONTROLLER://kafka-2:9093,PLAINTEXT_HOST://0.0.0.0:9092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:29092,PLAINTEXT_HOST://localhost:9094
#      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_LOG_DIRS: /kafka/data
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
#    command: [ "sh", "-c", "/opt/kafka/bin/kafka-server-start.sh /kafka/config/kraft.properties" ]
    command: [ "sh",  "-c", "/kafka/entrypoint.sh" ]
    networks:
      - kafka-net
  kafka-3:
    image: apache/kafka:3.7.0
    hostname: kafka-3
    container_name: kafka-3
    ports:
      - "9096:9096"
    volumes:
      - ./kafka-3/data:/kafka/data
      - ./kafka-3/kraft.properties:/kafka/config/kraft.properties
      - ./entrypoint.sh:/kafka/entrypoint.sh
    environment:
#      KAFKA_NODE_ID: 3
#      KAFKA_PROCESS_ROLES: broker,controller
#      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
#      KAFKA_LISTENERS: PLAINTEXT://kafka-3:29092,CONTROLLER://kafka-3:9093,PLAINTEXT_HOST://0.0.0.0:9092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:29092,PLAINTEXT_HOST://localhost:9096
#      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_LOG_DIRS: /kafka/data
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
#    command: [ "sh", "-c", "/opt/kafka/bin/kafka-server-start.sh /kafka/config/kraft.properties" ]
    command: [ "sh",  "-c", "/kafka/entrypoint.sh" ]
    networks:
      - kafka-net
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=kraft-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:29092,kafka-2:29092,kafka-3:29092
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    networks:
      - kafka-net
networks:
  kafka-net:
    driver: bridge